### ISSUE TITLE
What happened to this project?

### ISSUE THREAD

**Issue by YoukaiCat** [tlozovyi/LifeRPG-Tasks#1]
The latest tag is "1.3.1" while the latest version on Google Play is 1.6.2. 
The latest commit says that the code is temporarily moved to another repository. Where can I find that repository?
Is the project proprietary now?

**Comment by tlozovyi** [comment]
Project moved to private repo and is proprietary now. 
For questions or queries you can email to liferpgtasks@gmail.com.

**Comment by YoukaiCat** [comment]
It's sad to hear it. At the moment there is only one free (as in freedom) alternative as i know. But your application is better in my opinion.
Thank you for your work on this project. I'm closing this issue.
